on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build-appimage:
    runs-on: "ubuntu-latest"
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libgtk-3-dev libgtk-layer-shell-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add vendor libraries to resvg rust package
        run: ./install-resvg-vendor.sh

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: "3.32.2"
          channel: "stable"

      - uses: moonrepo/setup-rust@v1
        with:
          channel: "1.85.1"

      - name: Run flutter build linux
        run: flutter build linux

      - name: Create AppImage
        run: ./linux/create-appimage.sh

      - name: Create nix release zip
        run: ./linux/create-nix-release.sh ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            wayxec-x86_64.AppImage
            nix-release-x86_64.zip
